### ISSUE TITLE
Fix Opportunities section in mobile view

### ISSUE THREAD

**Issue by akanksha-raghav** [akanksha-raghav/Minor_Project#11]
Opportunities section in the mobile view seems overlapping of the first three divs.
![fix](https://user-images.githubusercontent.com/44342357/97796322-96dfe780-1c36-11eb-9cb4-cd19cf731172.JPG)

**Comment by chinmaym07** [comment]
Hey @akanksha-raghav  Can I do this. ?

**Comment by akanksha-raghav** [comment]
Yes please go ahead

**Comment by akanksha-raghav** [comment]
@chinmaym07 Any update?

**Comment by chinmaym07** [comment]
I have made a pr #12  .
Please review. :grinning:
