### ISSUE TITLE
Logos are not properly visible

### ISSUE THREAD

**Issue by akanksha-raghav** [akanksha-raghav/Minor_Project#19]
Some logos (Microsoft Student Ambassador, IBM champion) are not properly visible.
Go through every section and do the necessary changes

![logos](https://user-images.githubusercontent.com/44342357/137683760-6a700260-4720-4db7-94ab-93df864d0e58.png)

**Comment by irsayvid** [comment]
hey! would like to fix this. Can you assign this to me?
