### ISSUE TITLE
Fix redirect issue

### ISSUE THREAD

**Issue by Rupesh-Darimisetti** [akanksha-raghav/Minor_Project#21]
I would like to fix the redirect issue in mobile view so that it redirects to the respective page on clicking respective tag

**Comment by akanksha-raghav** [comment]
> I would like to fix the redirect issue in mobile view so that it redirects to the respective page on clicking the respective tag

kindly share the screenshots of the issue you are facing for a better review.

**Comment by Rupesh-Darimisetti** [comment]
![Screenshot_2021-10-20-21-19-50-976_com.android.chrome.jpg](https://user-images.githubusercontent.com/49586865/138127363-eaf577aa-983a-47a8-bbe7-893a316d8ad3.jpg)

On clicking the nav links.... It isn't redirecting to respective page

**Comment by akanksha-raghav** [comment]
okay please go ahead
