### ISSUE TITLE
Add newsletter section

### ISSUE THREAD

**Issue by akanksha-raghav** [akanksha-raghav/Minor_Project#4]
Add a newsletter section for subscribing.

**Comment by Denpex** [comment]
Hi @akanksha-raghav i would love to do this task. Newsletter section should be a simple form right (email input and submit button)?

**Comment by akanksha-raghav** [comment]
> Hi @akanksha-raghav i would love to do this task. Newsletter section should be a simple form right (email input and submit button)?

Sure @Denpex . Yes you are right!

**Comment by Denpex** [comment]
@akanksha-raghav I am currenctly participating in this years hacktoberfest so It would mean alot to me if you could add the topic "hacktoberfest" to your project so that I can get a pull request point :D

**Comment by akanksha-raghav** [comment]
Sure, labels been added
